version: '3.9'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: snippit
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula # theme
    ports:
      - 8080:8080